name: build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: theos/setup-theos-action@v1
      - name: Build
        run: make package FINALPACKAGE=1
      - name: Private
        uses: actions/upload-artifact@v4
        with:
          name: AhmedGram
          path: packages/*.deb
